### ISSUE TITLE
I tried to use it under iPhone8 PLUS iOS 13.6 panic happened.

### ISSUE THREAD

**Issue by tututu-patch** [googleprojectzero/ktrw#12]
panic : caught sync exception with interrupts held

![7631644252532_ pic_hd](https://user-images.githubusercontent.com/37355028/152833628-4d7ad038-2e7d-4c22-a545-23e9ee2b2f9b.jpg)

![7641644252532_ pic_hd](https://user-images.githubusercontent.com/37355028/152833765-015ef413-477e-453c-adb1-beb603ddb1cb.jpg)

The symbols file used : 
[iPhone10,1_17G68.txt](https://github.com/googleprojectzero/ktrw/files/8017091/iPhone10.1_17G68.txt)

**Comment by tututu-patch** [comment]
Looks like the offset is incorrect, I will check the offset.

**Comment by tututu-patch** [comment]
There is a problem with the offset detection, and he still panics under pongos after correcting the offset.
The symbols file used :
[iPhone10,1_17G68.txt](https://github.com/googleprojectzero/ktrw/files/8020642/iPhone10.1_17G68.txt)
![7711644293083_ pic_hd](https://user-images.githubusercontent.com/37355028/152916201-81c8adbb-3372-4ca1-9351-d64b60d3cc7e.jpg)

**Comment by 20000s** [comment]
how do you get these symbol files,i want to use ktrw to debug ios

**Comment by tututu-patch** [comment]
> There is a problem with the offset detection, and he still panics under pongos after correcting the offset. The symbols file used : [iPhone10,1_17G68.txt](https://github.com/googleprojectzero/ktrw/files/8020642/iPhone10.1_17G68.txt) ![7711644293083_ pic_hd](https://user-images.githubusercontent.com/37355028/152916201-81c8adbb-3372-4ca1-9351-d64b60d3cc7e.jpg)

This problem is due to an incompatibility issue caused by an update of the pongos SDK. I have tried to fix it before.

**Comment by tututu-patch** [comment]
Fix pull is https://github.com/googleprojectzero/ktrw/pull/14
