### ISSUE TITLE
Kernel Debugging for iOS 13.6

### ISSUE THREAD

**Issue by HarDToBelieve** [googleprojectzero/ktrw#9]
Hi,

I have an iPhone 8 Global running iOS 13.6, and I want to use KTRW + checkra1n for debugging kernel ( I have tested checkra1n with this device and kernel version and it works ). However I get no debug connection after following your instructions:
![image](https://user-images.githubusercontent.com/8986569/91525586-0af6ca00-e92c-11ea-8f14-6271a0c72158.png)
I guess that I need to create a new symbol file under `ktrw_gdb_stub/kernel_symbols/`
Is it enough to adapt KTRW on new iOS version or do I have to do anything else?

**Comment by HarDToBelieve** [comment]
I have updated `ktrw_gdb_stub/kernel_symbols/` for iOS 13.6 (iPhone10,1_17G68)  as below
```
KERNELCACHE UUID:	D94ABD59-5818-3D61-A459-7D56A3DE3E2F
DEVICE:		iPhone10,1 17G68

__disable_preemption	0xFFFFFFF007232604
__enable_preemption	0xFFFFFFF007232634
__mh_execute_header	0xFFFFFFF007004000
_const_boot_args	0xFFFFFFF0070D1BE0
_IOSleep		0xFFFFFFF007636AF4
_kernel_map		0xFFFFFFF0070D0A90
_kernel_memory_allocate	0xFFFFFFF0071BA558
_kernel_thread_start	0xFFFFFFF00716AB08
_ml_nofault_copy	0xFFFFFFF007238050
_panic			0xFFFFFFF0076E7C20
_paniclog_append_noflush	0xFFFFFFF007149854
_thread_deallocate	0xFFFFFFF007169294
_vsnprintf		0xFFFFFFF0075352B0
```
However, when `pongo_kext_loader` run to `Loading kernel extensions`, the kernel is panic as "Kernel instruction fetch abort" at the first instruction of `_kernel_thread_start` function. It should have run because I use checkra1n so I dont need to run KTRR.

any ideas how to fix this issue?

**Comment by brandonplank** [comment]
Hey, how are you supposed to get these offsets without symbols in the kernel?

**Comment by HarDToBelieve** [comment]
I just compare old version of kernel ( the one with symbol ) with the current version, then try to find out patterns based on string, byte opcode, ...

**Comment by tututu-patch** [comment]
@HarDToBelieve My device is iOS 13.6 (iPhone10,2_17G68) , but the offsets I found are these:
[iPhone10,1_17G68.txt](https://github.com/googleprojectzero/ktrw/files/8020582/iPhone10.1_17G68.txt)
